#!/bin/bash

# A timer for meditation

# Parse argument
if [[ $# -eq 0 ]]; then
    end=15
elif [[ $# -ne 1 ]]; then
    echo "Error: Bad usage: $0 [min]" >&2; exit 1
else
    end=$1
    re='^[0-9]+$'
    if ! [[ $end =~ $re ]]; then
        echo "Error: Not a number" >&2; exit 1
    fi
fi
max=$end

# Detect speaking software
if which say &>/dev/null; then
    speaker=say
elif which espeak &>/dev/null; then
    speaker=espeak
else
    speaker=echo
fi

# Start timer
i=0
echo "Meditating for $max minutes"
$speaker "begin"
while ((--end >= 0)); do
    sleep 60
    echo $((max - end))
done
$speaker "end"
echo "Meditation session complete"
