#!/bin/bash
# THIS DOESNT WORK

#tempfile="$(mktemp -u)"
#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'rpwd';" > "$tempfile"
#mysql.server stop &>/dev/null&
#mysqld --init-file="$tempfile" &>/dev/null&
#sleep 1
#rm -f ${tempfile}
#ps aux | grep mysqld | grep -v grep
#echo "Root pass: rpwd"
