#!/bin/bash

# A timer for meditation

# Special functions
play() {
    if which osascript &>/dev/null; then
        osascript -e 'tell application "Spotify" to play'
    fi
}

pause() {
    if which osascript &>/dev/null; then
        osascript -e 'tell application "Spotify" to pause'
    fi
}

usage() {
    echo "Usage: $0 [-mv] [-t min]"
    echo "    -m : stop spotify music, mac only"
    echo "    -v : say end"
    echo "    -t min : go for min minutes, default 45"
}

usage_quit() {
    usage
    exit
}

# Parse args
min=45
while getopts ":vmt:" opt; do
    case $opt in
        t) min="$OPTARG" ;;
        m) music=yes ;;
        v) voice=yes ;;
        \?) usage_quit ;;
    esac
done
shift $((OPTIND-1))

# Parse argument
if [[ $# -ne 0 ]]; then
    usage_quit
else
    re='^[0-9]+$'
    if ! [[ $min =~ $re ]]; then
        echo "Error: Not a number" >&2; exit 1
    fi
fi

# Detect speaking software
if which say &>/dev/null; then
    speaker=say
elif which espeak &>/dev/null; then
    speaker=espeak
else
    speaker=echo
fi

# Start timer
max=$min
echo "Timer for $max minutes"
echo "Begin"
while ((--min >= 0)); do
    sleep 60
    echo $((max - min))
done
echo "Timer complete"
if [ $music ]; then
    pause
fi
if [ $voice ]; then
    $speaker "end"
fi
