#!/usr/bin/env python

import sys
import re
import pandas as pd

for fin in sys.argv[1:]:
    try:
        fout = re.sub('xlsx$', 'csv', fin)
        pd.read_excel(fin).to_csv(fout, index=False)
    except FileNotFoundError:
        print(f"Error: File not found: {fin}")
    except:
        raise
